#define module_driver

#include "stepdance.hpp"

// input and output setup
OutputPort output_a; // x axis belt
OutputPort output_b; // y axis belt
OutputPort output_c; // z axis (height)
OutputPort output_d; // stepper extruder

Channel channel_a; // x
Channel channel_b; // y
Channel channel_z; // z
Channel channel_e; // extruder

// dependencies
KinematicsPolarToCartesian polar_kinematics;
PositionGenerator position_gen; 
VelocityGenerator velocity_gen;
VelocityGenerator extrusion_gen;
TimeBasedInterpolator time_based_interpolator;

Encoder encoder_1; // RADIUS
Encoder encoder_2; // Z AXIS

ScalingFilter1D drip_filter;
const float64_t dripRate = 5.0;

Button button_d1; // start button
Button button_d2; // fix extruder position (+)

AnalogInput analog_a1; // potentiometer for driprate
AnalogInput analog_a2; // potentiometer for fix extruder position (-)

RPC rpc; // remote procedure call

// const float64_t FIXED_RADIUS = 20.0; 
float64_t currentSpeed = 1.0;        // tune via serial


void setup() {
  // opening serial port
  Serial.begin(115200);

  // mapping inputs
  output_a.begin(OUTPUT_A);
  output_b.begin(OUTPUT_B);
  output_c.begin(OUTPUT_C);
  output_d.begin(OUTPUT_D);

  // Allows the inputs and outputs to talk with the board
  enable_drivers();

  // Mapping the outputs
  channel_a.begin(&output_a, SIGNAL_E);
  channel_a.set_ratio(1, 40);
  channel_a.invert_output();

  channel_b.begin(&output_b, SIGNAL_E);
  channel_b.set_ratio(1, 40);

  channel_z.begin(&output_c, SIGNAL_E);
  channel_z.set_ratio(1, 1201);
  channel_z.invert_output();

  channel_e.begin(&output_d, SIGNAL_E);
  channel_e.set_ratio(2, 200);

  // map the signal generated by position_gen to the E channel
  position_gen.output.map(&channel_e.input_target_position);
  // any plugin must call begin
  position_gen.begin();

  // Initialize function that runs in loop
  drip_filter.begin();
  drip_filter.set_ratio(dripRate, TWO_PI); 
  // updates rate of extrusion and maps value to the stepper motor pushing the syringe
  drip_filter.input.map(&polar_kinematics.input_angle);
  drip_filter.output.map(&channel_e.input_target_position);

  // potentiometer to adjust dripRate, value is sent to drip_filter in loop
  analog_a1.set_floor(0, 25);
  analog_a1.set_ceiling(3, 1020);
  analog_a1.begin(IO_A1);

  // potentiometer to move upper platform down, value is sent to ()
  analog_a2.set_floor(0, 25);
  analog_a2.set_ceiling(3, 1020);
  analog_a2.begin(IO_A2);
  

  // Zero-ing XY axis
  button_d1.begin(IO_D1, INPUT_PULLDOWN);
  button_d1.set_mode(BUTTON_MODE_STANDARD);
  button_d1.set_callback_on_press(&zeroingAxis);

  // Fix extruder position
  button_d2.begin(IO_D2, INPUT_PULLDOWN);
  button_d2.set_mode(BUTTON_MODE_STANDARD);
  button_d2.set_callback_on_press(&raiseExtruder);

  // Initializes the velocity_gen function
  velocity_gen.begin();

  // Controls the speed of the the angle 
  velocity_gen.speed_units_per_sec = currentSpeed;
  velocity_gen.output.map(&polar_kinematics.input_angle);

  // Initializes the extrusion_gen function
  extrusion_gen.begin();
  // Control the speed of the downward velocity of the extruder
  extrusion_gen.speed_units_per_sec = 0.0;
  extrusion_gen.output.map(&channel_e.input_target_position);


  // extruder
  encoder_1.begin(ENCODER_1);
  encoder_1.set_ratio(4, 2400);
  encoder_1.output.map(&polar_kinematics.input_radius); 
  //encoder_1.output.map(&channel_a.input_target_position); 

  // Z axis
  encoder_2.begin(ENCODER_2);
  encoder_2.set_ratio(2, 2400);
  encoder_2.output.map(&channel_z.input_target_position);

  // Initializes polar_kinematics
  // Translates from polar coordinates to cartesian coordinates
  polar_kinematics.begin();
  polar_kinematics.output_x.map(&channel_a.input_target_position);
  polar_kinematics.output_y.map(&channel_b.input_target_position);

  // Initialize remote procedure call to adjust the extrusion rate
  rpc.begin(); 
  rpc.enroll("hello", hello_serial);

  // Call example: {"name": "tuneExtruder", "args": [1]}
  rpc.enroll("tuneExtruder", tuneExtruder);

  // Initialize time-based interpolator for time-dependent events
  time_based_interpolator.begin();
  time_based_interpolator.output_x.map(&channel_a.input_target_position);
  time_based_interpolator.output_y.map(&channel_b.input_target_position);

  // Begin running stepdance
  dance_start();
}

LoopDelay overhead_delay;

// Dance loop
void loop() {
  //overhead_delay.periodic_call(&report_overhead, 500);

  // if (Serial.available()) { 
  //   float newSpeed = Serial.parseFloat();
  //   if (newSpeed > 0) {
  //     currentSpeed = newSpeed;
  //     velocity_gen.speed_units_per_sec = currentSpeed;
  //   }
  // }

  // user-adjustable extrusion rate
  float64_t dripMultiplier = analog_a1.read();
  drip_filter.set_ratio(dripRate*dripMultiplier,TWO_PI);

  float64_t speedExtrusion = analog_a2.read();
  extrusion_gen.speed_units_per_sec = speedExtrusion;

  // Loops the program, runs until power-off
  dance_loop();
}


void hello_serial(){
  Serial.print("hello!");
}

// RPC calls this function
void tuneExtruder(float32_t val){
  Serial.print("push!");
  position_gen.go(val, INCREMENTAL, 10);
}

// Button D2 callback: fix extruder position (-50)
void raiseExtruder() {
  Serial.println("Fixing extruder position (+)");
  position_gen.go(-50, INCREMENTAL, 10);
}

// Reports back how fast the circle in the angle direction is being drawn 
void report_overhead() {
  // Serial.print("speed (rad/s): ");
  // Serial.println(currentSpeed);
  // zeroingAxis();
}


void zeroingAxis() {
  Serial.println("Zeroing Y and X Axis");
  // time_based_interpolator.begin();
  time_based_interpolator.add_move(GLOBAL, 30.0, -214.49, -384.41,0,0,0,0);

  // Serial.println("Finishing Zeroing Y and X Axis");

  // Serial.println(channel_a.input_target_position.read(ABSOLUTE));

}